/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_wasmvec2_free(a: number): void;
export function __wbg_get_wasmvec2_0(a: number): number;
export function __wbg_set_wasmvec2_0(a: number, b: number): void;
export function __wbg_get_wasmvec2_1(a: number): number;
export function __wbg_set_wasmvec2_1(a: number, b: number): void;
export function wasmvec2_new(a: number, b: number): number;
export function __wbg_wasmvec3_free(a: number): void;
export function __wbg_get_wasmvec3_2(a: number): number;
export function __wbg_set_wasmvec3_2(a: number, b: number): void;
export function wasmvec3_new(a: number, b: number, c: number): number;
export function __wbg_scenecamerasettings_free(a: number): void;
export function __wbg_get_scenecamerasettings_size(a: number): number;
export function __wbg_set_scenecamerasettings_size(a: number, b: number): void;
export function __wbg_get_scenecamerasettings_look_at(a: number): number;
export function __wbg_set_scenecamerasettings_look_at(a: number, b: number): void;
export function __wbg_get_scenecamerasettings_distance(a: number): number;
export function __wbg_set_scenecamerasettings_distance(a: number, b: number): void;
export function __wbg_get_scenecamerasettings_rotation(a: number): number;
export function __wbg_set_scenecamerasettings_rotation(a: number, b: number): void;
export function scenecamerasettings_new(): number;
export function __wbg_scenelightingsettings_free(a: number): void;
export function __wbg_get_scenelightingsettings_direction(a: number): number;
export function __wbg_set_scenelightingsettings_direction(a: number, b: number): void;
export function __wbg_get_scenelightingsettings_intensity(a: number): number;
export function __wbg_set_scenelightingsettings_intensity(a: number, b: number): void;
export function __wbg_get_scenelightingsettings_ambient(a: number): number;
export function __wbg_set_scenelightingsettings_ambient(a: number, b: number): void;
export function scenelightingsettings_new(): number;
export function __wbg_scenecharactersettings_free(a: number): void;
export function __wbg_get_scenecharactersettings_is_slim(a: number): number;
export function __wbg_set_scenecharactersettings_is_slim(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_hat_layer(a: number): number;
export function __wbg_set_scenecharactersettings_has_hat_layer(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_ears(a: number): number;
export function __wbg_set_scenecharactersettings_has_ears(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_layers(a: number): number;
export function __wbg_set_scenecharactersettings_has_layers(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_cape(a: number): number;
export function __wbg_set_scenecharactersettings_has_cape(a: number, b: number): void;
export function scenecharactersettings_new(): number;
export function setup_scene(a: number, b: number, c: number, d: number, e: number): number;
export function get_camera(): number;
export function get_sun(): number;
export function notify_mouse_down(): number;
export function notify_mouse_up(): number;
export function notify_mouse_move(a: number, b: number): number;
export function notify_mouse_scroll(a: number): number;
export function render_frame(): number;
export function initialize(a: number, b: number, c: number): number;
export function __wbg_set_wasmvec3_0(a: number, b: number): void;
export function __wbg_set_wasmvec3_1(a: number, b: number): void;
export function set_camera_rotation(a: number, b: number, c: number): void;
export function __wbg_get_wasmvec3_0(a: number): number;
export function __wbg_get_wasmvec3_1(a: number): number;
export function wgpu_render_bundle_set_bind_group(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_bundle_set_pipeline(a: number, b: number): void;
export function wgpu_render_bundle_set_vertex_buffer(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_bundle_set_index_buffer(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_bundle_set_push_constants(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_bundle_draw(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_bundle_draw_indexed(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function wgpu_render_bundle_draw_indirect(a: number, b: number, c: number): void;
export function wgpu_render_bundle_draw_indexed_indirect(a: number, b: number, c: number): void;
export function wgpu_render_bundle_pop_debug_group(a: number): void;
export function wgpu_render_bundle_insert_debug_marker(a: number, b: number): void;
export function wgpu_compute_pass_set_bind_group(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_compute_pass_set_pipeline(a: number, b: number): void;
export function wgpu_compute_pass_set_push_constant(a: number, b: number, c: number, d: number): void;
export function wgpu_compute_pass_dispatch_workgroups(a: number, b: number, c: number, d: number): void;
export function wgpu_compute_pass_dispatch_workgroups_indirect(a: number, b: number, c: number): void;
export function wgpu_compute_pass_push_debug_group(a: number, b: number, c: number): void;
export function wgpu_compute_pass_pop_debug_group(a: number): void;
export function wgpu_compute_pass_insert_debug_marker(a: number, b: number, c: number): void;
export function wgpu_compute_pass_write_timestamp(a: number, b: number, c: number): void;
export function wgpu_compute_pass_begin_pipeline_statistics_query(a: number, b: number, c: number): void;
export function wgpu_compute_pass_end_pipeline_statistics_query(a: number): void;
export function wgpu_render_pass_set_bind_group(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_pass_set_pipeline(a: number, b: number): void;
export function wgpu_render_pass_set_vertex_buffer(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_pass_set_index_buffer(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_pass_set_blend_constant(a: number, b: number): void;
export function wgpu_render_pass_set_stencil_reference(a: number, b: number): void;
export function wgpu_render_pass_set_viewport(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function wgpu_render_pass_set_scissor_rect(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_pass_set_push_constants(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_pass_draw(a: number, b: number, c: number, d: number, e: number): void;
export function wgpu_render_pass_draw_indexed(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function wgpu_render_pass_draw_indirect(a: number, b: number, c: number): void;
export function wgpu_render_pass_draw_indexed_indirect(a: number, b: number, c: number): void;
export function wgpu_render_pass_multi_draw_indirect(a: number, b: number, c: number, d: number): void;
export function wgpu_render_pass_multi_draw_indexed_indirect(a: number, b: number, c: number, d: number): void;
export function wgpu_render_pass_multi_draw_indirect_count(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function wgpu_render_pass_multi_draw_indexed_indirect_count(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function wgpu_render_pass_push_debug_group(a: number, b: number, c: number): void;
export function wgpu_render_pass_pop_debug_group(a: number): void;
export function wgpu_render_pass_insert_debug_marker(a: number, b: number, c: number): void;
export function wgpu_render_pass_write_timestamp(a: number, b: number, c: number): void;
export function wgpu_render_pass_begin_occlusion_query(a: number, b: number): void;
export function wgpu_render_pass_end_occlusion_query(a: number): void;
export function wgpu_render_pass_begin_pipeline_statistics_query(a: number, b: number, c: number): void;
export function wgpu_render_pass_end_pipeline_statistics_query(a: number): void;
export function wgpu_render_pass_execute_bundles(a: number, b: number, c: number): void;
export function wgpu_render_bundle_push_debug_group(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke1_mut__h9613721940482ee8(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h1d744d890e1b408e(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h93dddc09c5782875(a: number, b: number, c: number, d: number): void;
