/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_wasmvec2_free(a: number): void;
export function __wbg_get_wasmvec2_0(a: number): number;
export function __wbg_set_wasmvec2_0(a: number, b: number): void;
export function __wbg_get_wasmvec2_1(a: number): number;
export function __wbg_set_wasmvec2_1(a: number, b: number): void;
export function wasmvec2_new(a: number, b: number): number;
export function __wbg_wasmvec3_free(a: number): void;
export function __wbg_get_wasmvec3_2(a: number): number;
export function __wbg_set_wasmvec3_2(a: number, b: number): void;
export function wasmvec3_new(a: number, b: number, c: number): number;
export function __wbg_scenecamerasettings_free(a: number): void;
export function __wbg_get_scenecamerasettings_size(a: number): number;
export function __wbg_set_scenecamerasettings_size(a: number, b: number): void;
export function __wbg_get_scenecamerasettings_look_at(a: number): number;
export function __wbg_set_scenecamerasettings_look_at(a: number, b: number): void;
export function __wbg_get_scenecamerasettings_distance(a: number): number;
export function __wbg_set_scenecamerasettings_distance(a: number, b: number): void;
export function __wbg_get_scenecamerasettings_rotation(a: number): number;
export function __wbg_set_scenecamerasettings_rotation(a: number, b: number): void;
export function scenecamerasettings_new(): number;
export function __wbg_scenelightingsettings_free(a: number): void;
export function __wbg_get_scenelightingsettings_direction(a: number): number;
export function __wbg_set_scenelightingsettings_direction(a: number, b: number): void;
export function __wbg_get_scenelightingsettings_intensity(a: number): number;
export function __wbg_set_scenelightingsettings_intensity(a: number, b: number): void;
export function __wbg_get_scenelightingsettings_ambient(a: number): number;
export function __wbg_set_scenelightingsettings_ambient(a: number, b: number): void;
export function scenelightingsettings_new(): number;
export function __wbg_scenecharactersettings_free(a: number): void;
export function __wbg_get_scenecharactersettings_is_slim(a: number): number;
export function __wbg_set_scenecharactersettings_is_slim(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_hat_layer(a: number): number;
export function __wbg_set_scenecharactersettings_has_hat_layer(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_ears(a: number): number;
export function __wbg_set_scenecharactersettings_has_ears(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_layers(a: number): number;
export function __wbg_set_scenecharactersettings_has_layers(a: number, b: number): void;
export function __wbg_get_scenecharactersettings_has_cape(a: number): number;
export function __wbg_set_scenecharactersettings_has_cape(a: number, b: number): void;
export function scenecharactersettings_new(): number;
export function setup_scene(a: number, b: number, c: number, d: number, e: number): number;
export function get_camera(): number;
export function get_sun(): number;
export function notify_mouse_down(): number;
export function notify_mouse_up(): number;
export function notify_mouse_move(a: number, b: number): number;
export function notify_mouse_scroll(a: number): number;
export function render_frame(): number;
export function initialize(a: number, b: number, c: number): number;
export function __wbg_set_wasmvec3_0(a: number, b: number): void;
export function __wbg_set_wasmvec3_1(a: number, b: number): void;
export function set_camera_rotation(a: number, b: number, c: number): void;
export function __wbg_get_wasmvec3_0(a: number): number;
export function __wbg_get_wasmvec3_1(a: number): number;
export const __wbindgen_export_0: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke1_mut__h11459d96e65899c2(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h1f66deadffc708a9(a: number, b: number, c: number, d: number): void;
